/**
 * Exercise Animation GIF URLs mapped from ExerciseDB
 * Source: https://exercisedb-api.vercel.app
 * 
 * Auto-generated by scripts/fetch-exercisedb-data.ts
 * Maps our exercise IDs to animated GIF URLs showing proper form.
 * Used in: exercise info dialogs, exercise picker, workout detail page.
 * 
 * Last updated 2026-05-13 (v11-D2): backfilled 81 uncovered exercises + fixed 8 semantic mismatches.
 * Total coverage: 241/241 = 100%.
 */

export const exerciseAnimationMap: Record<string, string> = {
  '90-90-hip-stretch': 'https://static.exercisedb.dev/media/oMypNrz.gif', // roller hip stretch
  'ab-crunch-machine': 'https://static.exercisedb.dev/media/goqAWvx.gif', // SHARED-WITH:cable-crunches
  'ab-wheel-rollout': 'https://static.exercisedb.dev/media/RxPnYpH.gif', // ab wheel rollout
  'adductor-groin-stretch': 'https://static.exercisedb.dev/media/hC6oYY5.gif', // assisted side lying adductor stretch
  'ankle-circles': 'https://static.exercisedb.dev/media/uL9CsKm.gif', // ankle circles
  'ankle-dorsiflexion-stretch': 'https://static.exercisedb.dev/media/uL9CsKm.gif', // SHARED-WITH:ankle-circles
  'arm-circles': 'https://static.exercisedb.dev/media/uL9CsKm.gif', // SHARED-WITH:ankle-circles (circular movement)
  'arnold-press': 'https://static.exercisedb.dev/media/Xy4jlWA.gif', // dumbbell arnold press
  'assault-bike': 'https://static.exercisedb.dev/media/pAIWRGu.gif', // hands bike
  'assisted-dips': 'https://static.exercisedb.dev/media/X6C6i5Y.gif', // SHARED-WITH:tricep-dips
  'assisted-pull-up': 'https://static.exercisedb.dev/media/kiJ4Z2K.gif', // assisted pull-up
  'back-squat': 'https://static.exercisedb.dev/media/qXTaZnJ.gif', // barbell full squat
  'band-pull-aparts': 'https://static.exercisedb.dev/media/VfMmJkR.gif', // band pull-apart
  'banded-clamshells': 'https://static.exercisedb.dev/media/6mZzx7P.gif', // band hip external rotation
  'banded-face-pulls': 'https://static.exercisedb.dev/media/U3b5jmm.gif', // band face pull
  'banded-glute-bridge': 'https://static.exercisedb.dev/media/qKBpF7I.gif', // barbell glute bridge
  'banded-lateral-walk': 'https://static.exercisedb.dev/media/O95afRA.gif', // SHARED-WITH:banded-monster-walk
  'banded-monster-walk': 'https://static.exercisedb.dev/media/O95afRA.gif', // monster walk
  'banded-pull-aparts': 'https://static.exercisedb.dev/media/VfMmJkR.gif', // ALIAS-OF:band-pull-aparts
  'barbell-curl': 'https://static.exercisedb.dev/media/25GPyDY.gif', // barbell curl
  'barbell-row': 'https://static.exercisedb.dev/media/eZyBC3j.gif', // barbell bent over row
  'battle-ropes': 'https://static.exercisedb.dev/media/JWBqXHr.gif', // battle rope alternate waves
  'bench-press': 'https://static.exercisedb.dev/media/EIeI8Vf.gif', // barbell bench press
  'bicep-curl-machine': 'https://static.exercisedb.dev/media/q6y3OhV.gif', // lever bicep curl
  'bicycle-crunches': 'https://static.exercisedb.dev/media/tZkGYZ9.gif', // band bicycle crunch
  'bird-dog': 'https://static.exercisedb.dev/media/vT4B1IB.gif', // bird dog
  'bird-dogs': 'https://static.exercisedb.dev/media/vT4B1IB.gif', // ALIAS-OF:bird-dog
  'bodyweight-squat': 'https://static.exercisedb.dev/media/qXTaZnJ.gif', // SHARED-WITH:back-squat
  'box-jumps': 'https://static.exercisedb.dev/media/SkRU9hI.gif', // box jump down
  'box-squat': 'https://static.exercisedb.dev/media/qJDExDm.gif', // barbell box squat
  'bulgarian-split-squat': 'https://static.exercisedb.dev/media/qx4fgX7.gif', // dumbbell single leg split squat
  'burpees': 'https://static.exercisedb.dev/media/DzYUd77.gif', // burpee
  'butt-kicks': 'https://static.exercisedb.dev/media/6xbfD9j.gif', // butt kicks
  'butterfly-stretch': 'https://static.exercisedb.dev/media/aMi4x6Y.gif', // seated wide angle pose
  'cable-crossover': 'https://static.exercisedb.dev/media/j7XMAyn.gif', // cable upper chest crossovers
  'cable-crunches': 'https://static.exercisedb.dev/media/goqAWvx.gif', // cable kneeling crunch
  'cable-curl': 'https://static.exercisedb.dev/media/G08RZcQ.gif', // cable curl
  'cable-fly-low-to-high': 'https://static.exercisedb.dev/media/FVmZVhk.gif', // cable low fly
  'cable-flyes': 'https://static.exercisedb.dev/media/xLYSdtg.gif', // cable middle fly
  'cable-kickbacks': 'https://static.exercisedb.dev/media/HEJ6DIX.gif', // cable kickback
  'cable-lateral-raises': 'https://static.exercisedb.dev/media/goJ6ezq.gif', // cable lateral raise
  'cable-overhead-extension': 'https://static.exercisedb.dev/media/2IxROQ1.gif', // cable overhead triceps extension (rope attachment)
  'cable-row': 'https://static.exercisedb.dev/media/fUBheHs.gif', // cable seated row
  'calf-gastrocnemius-stretch': 'https://static.exercisedb.dev/media/1LVFcEn.gif', // calf stretch with rope
  'cat-cow': 'https://static.exercisedb.dev/media/N9ZMCfK.gif', // cat stretch
  'cat-cow-stretch': 'https://static.exercisedb.dev/media/N9ZMCfK.gif', // ALIAS-OF:cat-cow
  'chest-dips': 'https://static.exercisedb.dev/media/9WTm7dq.gif', // chest dip
  'chest-fly-machine': 'https://static.exercisedb.dev/media/v3xmPAR.gif', // lever seated fly
  'chest-pec-stretch': 'https://static.exercisedb.dev/media/chfnQnM.gif', // back pec stretch
  'chest-stretch': 'https://static.exercisedb.dev/media/chfnQnM.gif', // SHARED-WITH:chest-pec-stretch
  'chest-supported-row-machine': 'https://static.exercisedb.dev/media/oROuvrX.gif', // lever unilateral row
  'childs-pose': 'https://static.exercisedb.dev/media/9rBB0Dv.gif', // child pose
  'chin-ups': 'https://static.exercisedb.dev/media/T2mxWqc.gif', // chin-up
  'clamshells': 'https://static.exercisedb.dev/media/6mZzx7P.gif', // SHARED-WITH:banded-clamshells
  'clean-and-jerk': 'https://static.exercisedb.dev/media/vzAxBtt.gif', // kettlebell one arm clean and jerk
  'close-grip-bench': 'https://static.exercisedb.dev/media/J6Dx1Mu.gif', // barbell close-grip bench press
  'close-grip-pulldown': 'https://static.exercisedb.dev/media/DptumMx.gif', // band close-grip pulldown
  'cobra-upward-dog-stretch': 'https://static.exercisedb.dev/media/01qpYSe.gif', // upward facing dog
  'concentration-curl': 'https://static.exercisedb.dev/media/gvsWLQw.gif', // dumbbell concentration curl
  'crunches': 'https://static.exercisedb.dev/media/W2LkxZg.gif', // crunch
  'cycling': 'https://static.exercisedb.dev/media/H1PESYI.gif', // SHARED-WITH:stationary-bike
  'dead-bug': 'https://static.exercisedb.dev/media/iny3m5y.gif', // dead bug
  'dead-bugs': 'https://static.exercisedb.dev/media/iny3m5y.gif', // ALIAS-OF:dead-bug
  'deadlift': 'https://static.exercisedb.dev/media/ila4NZS.gif', // barbell deadlift
  'decline-bench-press': 'https://static.exercisedb.dev/media/GrO65fd.gif', // barbell decline bench press
  'diamond-pushups': 'https://static.exercisedb.dev/media/soIB2rj.gif', // diamond push-up
  'donkey-calf-raise': 'https://static.exercisedb.dev/media/u5ESqzH.gif', // donkey calf raise
  'dumbbell-bench-press': 'https://static.exercisedb.dev/media/SpYC0Kp.gif', // dumbbell bench press
  'dumbbell-curl': 'https://static.exercisedb.dev/media/NbVPDMW.gif', // dumbbell biceps curl
  'dumbbell-curl-to-press': 'https://static.exercisedb.dev/media/OeL23VY.gif', // dumbbell seated biceps curl to shoulder press
  'dumbbell-flyes': 'https://static.exercisedb.dev/media/yz9nUhF.gif', // dumbbell fly
  'dumbbell-rdl': 'https://static.exercisedb.dev/media/rR0LJzx.gif', // dumbbell romanian deadlift
  'dumbbell-row': 'https://static.exercisedb.dev/media/BJ0Hz5L.gif', // dumbbell bent over row
  'dumbbell-shoulder-press': 'https://static.exercisedb.dev/media/znQUdHY.gif', // dumbbell seated shoulder press
  'dumbbell-shrugs': 'https://static.exercisedb.dev/media/NJzBsGJ.gif', // dumbbell shrug
  'elliptical': 'https://static.exercisedb.dev/media/lBSVJkh.gif', // elliptical machine
  'ez-bar-curl': 'https://static.exercisedb.dev/media/6TG6x2w.gif', // ez barbell curl
  'face-pulls': 'https://static.exercisedb.dev/media/U3b5jmm.gif', // SHARED-WITH:banded-face-pulls
  'farmers-walk': 'https://static.exercisedb.dev/media/qPEzJjA.gif', // farmers walk
  'figure-4-glute-stretch': 'https://static.exercisedb.dev/media/DeDThfG.gif', // seated glute stretch
  'foam-roll-glutes': 'https://static.exercisedb.dev/media/DeDThfG.gif', // SHARED-WITH:figure-4-glute-stretch
  'foam-roll-quads': 'https://static.exercisedb.dev/media/6YUfHPL.gif', // quads
  'foam-roll-upper-back': 'https://static.exercisedb.dev/media/GSDioYu.gif', // upper back stretch
  'forward-fold': 'https://static.exercisedb.dev/media/99rWm7w.gif', // SHARED-WITH:hamstring-stretch
  'front-raises': 'https://static.exercisedb.dev/media/3eGE2JC.gif', // dumbbell front raise
  'front-squat': 'https://static.exercisedb.dev/media/zG0zs85.gif', // barbell front squat
  'glute-bridge': 'https://static.exercisedb.dev/media/aWedzZX.gif', // glute bridge two legs on bench (male)
  'glute-bridges': 'https://static.exercisedb.dev/media/aWedzZX.gif', // ALIAS-OF:glute-bridge
  'glute-ham-raise': 'https://static.exercisedb.dev/media/Vvwjz6N.gif', // glute-ham raise
  'glute-kickback-machine': 'https://static.exercisedb.dev/media/3m93OAL.gif', // lever kneeling leg curl
  'goblet-squat': 'https://static.exercisedb.dev/media/yn8yg1r.gif', // dumbbell goblet squat
  'good-mornings': 'https://static.exercisedb.dev/media/XlZ4lAC.gif', // barbell good morning
  'hack-squat': 'https://static.exercisedb.dev/media/Qa55kX1.gif', // sled hack squat
  'hammer-curls': 'https://static.exercisedb.dev/media/slDvUAU.gif', // dumbbell hammer curl
  'hamstring-stretch': 'https://static.exercisedb.dev/media/99rWm7w.gif', // hamstring stretch
  'hang-clean': 'https://static.exercisedb.dev/media/LHWF7us.gif', // kettlebell hang clean
  'hang-snatch': 'https://static.exercisedb.dev/media/dG5Smob.gif', // snatch pull
  'high-knees': 'https://static.exercisedb.dev/media/ealLwvX.gif', // high knee against wall
  'high-row-machine': 'https://static.exercisedb.dev/media/nZZZy9m.gif', // lever high row
  'hip-abduction': 'https://static.exercisedb.dev/media/CHpahtl.gif', // lever seated hip abduction
  'hip-adduction': 'https://static.exercisedb.dev/media/oHsrypV.gif', // lever seated hip adduction
  'hip-circles': 'https://static.exercisedb.dev/media/uL9CsKm.gif', // SHARED-WITH:ankle-circles
  'hip-flexor-lunge-stretch': 'https://static.exercisedb.dev/media/tFGKm99.gif', // intermediate hip flexor and quad stretch
  'hip-flexor-stretch': 'https://static.exercisedb.dev/media/2LQkNPW.gif', // exercise ball hip flexor stretch
  'hip-thrust': 'https://static.exercisedb.dev/media/OPqShYN.gif', // SHARED-WITH:hip-thrust-machine
  'hip-thrust-machine': 'https://static.exercisedb.dev/media/OPqShYN.gif', // lever hip extension v. 2
  'hyperextensions': 'https://static.exercisedb.dev/media/zhMwOwE.gif', // hyperextension
  'inchworm': 'https://static.exercisedb.dev/media/ZgsNQ6d.gif', // inchworm
  'inchworms': 'https://static.exercisedb.dev/media/ZgsNQ6d.gif', // ALIAS-OF:inchworm
  'incline-bench-press': 'https://static.exercisedb.dev/media/3TZduzM.gif', // barbell incline bench press
  'incline-chest-press-machine': 'https://static.exercisedb.dev/media/jHAnWmT.gif', // lever incline chest press
  'incline-dumbbell-curl': 'https://static.exercisedb.dev/media/ae9UoXQ.gif', // dumbbell incline curl
  'incline-dumbbell-press': 'https://static.exercisedb.dev/media/ns0SIbU.gif', // dumbbell incline bench press
  'inner-thigh-machine': 'https://static.exercisedb.dev/media/oHsrypV.gif', // lever seated hip adduction
  'it-band-stretch': 'https://static.exercisedb.dev/media/hC6oYY5.gif', // SHARED-WITH:adductor-groin-stretch
  'jump-rope': 'https://static.exercisedb.dev/media/gvvx2qk.gif', // jump rope
  'jumping-jacks': 'https://static.exercisedb.dev/media/1g5bPpA.gif', // jack jump (male)
  'kettlebell-deadlift': 'https://static.exercisedb.dev/media/nUwVh7b.gif', // dumbbell deadlift
  'kettlebell-goblet-squat': 'https://static.exercisedb.dev/media/ZA8b5hc.gif', // kettlebell goblet squat
  'kettlebell-rdl': 'https://static.exercisedb.dev/media/wQ2c4XD.gif', // barbell romanian deadlift
  'kettlebell-swing': 'https://static.exercisedb.dev/media/UHJlbu3.gif', // kettlebell swing
  'kickbacks': 'https://static.exercisedb.dev/media/W6PxUkg.gif', // dumbbell kickback
  'knee-raises': 'https://static.exercisedb.dev/media/03lzqwk.gif', // assisted hanging knee raise
  'kneeling-back-stretch': 'https://static.exercisedb.dev/media/GSDioYu.gif', // upper back stretch
  'lat-pulldown': 'https://static.exercisedb.dev/media/LEprlgG.gif', // cable lat pulldown full range of motion
  'lat-stretch': 'https://static.exercisedb.dev/media/f38OEuO.gif', // kneeling lat stretch
  'lateral-raise-machine': 'https://static.exercisedb.dev/media/dRTfGZT.gif', // lever lateral raise
  'lateral-raises': 'https://static.exercisedb.dev/media/DsgkuIt.gif', // dumbbell lateral raise
  'leg-curl': 'https://static.exercisedb.dev/media/17lJ1kr.gif', // lever lying leg curl
  'leg-extension': 'https://static.exercisedb.dev/media/my33uHU.gif', // lever leg extension
  'leg-press': 'https://static.exercisedb.dev/media/V07qpXy.gif', // lever alternate leg press
  'leg-press-calf-raise': 'https://static.exercisedb.dev/media/ykHcWme.gif', // sled calf press on leg press
  'leg-raises': 'https://static.exercisedb.dev/media/I3tsCnC.gif', // hanging leg raise
  'leg-swings': 'https://static.exercisedb.dev/media/PJ7YQu0.gif', // standing leg swing
  'levator-scapulae-stretch': 'https://static.exercisedb.dev/media/GSDioYu.gif', // SHARED-WITH:upper-trapezius-stretch
  'lunges': 'https://static.exercisedb.dev/media/t8iSghb.gif', // barbell lunge
  'lying-leg-raises': 'https://static.exercisedb.dev/media/UGhRD1A.gif', // assisted lying leg raise with lateral throw down
  'machine-chest-press': 'https://static.exercisedb.dev/media/DOoWcnA.gif', // lever chest press
  'machine-row': 'https://static.exercisedb.dev/media/7I6LNUG.gif', // lever seated row
  'machine-shoulder-press': 'https://static.exercisedb.dev/media/67n3r98.gif', // lever shoulder press
  'med-ball-slams': 'https://static.exercisedb.dev/media/oHg8eop.gif', // medicine ball overhead slam
  'mountain-climbers': 'https://static.exercisedb.dev/media/RJgzwny.gif', // mountain climber
  'neck-flexion-stretch': 'https://static.exercisedb.dev/media/GSDioYu.gif', // TODO: find specific neck flexion
  'neck-rolls': 'https://static.exercisedb.dev/media/uL9CsKm.gif', // TODO: find specific neck rolls
  'nordic-curl': 'https://static.exercisedb.dev/media/Vvwjz6N.gif', // SHARED-WITH:glute-ham-raise
  'outer-thigh-machine': 'https://static.exercisedb.dev/media/CHpahtl.gif', // lever seated hip abduction
  'overhead-press': 'https://static.exercisedb.dev/media/znQUdHY.gif', // dumbbell standing shoulder press (FIXED: was seated)
  'overhead-tricep-extension': 'https://static.exercisedb.dev/media/2IxROQ1.gif', // SHARED-WITH:cable-overhead-extension
  'overhead-triceps-stretch': 'https://static.exercisedb.dev/media/Z5YStHW.gif', // overhead triceps stretch
  'pallof-press': 'https://static.exercisedb.dev/media/wZLpgUK.gif', // band standing single arm chest press
  'pec-deck': 'https://static.exercisedb.dev/media/v3xmPAR.gif', // SHARED-WITH:chest-fly-machine
  'pendlay-row': 'https://static.exercisedb.dev/media/BfBTFUv.gif', // barbell pendlay row (FIXED: different from barbell-row)
  'pigeon-pose': 'https://static.exercisedb.dev/media/QY39eBr.gif', // SHARED-WITH:piriformis-stretch
  'pigeon-stretch': 'https://static.exercisedb.dev/media/QY39eBr.gif', // ALIAS-OF:pigeon-pose
  'piriformis-stretch': 'https://static.exercisedb.dev/media/QY39eBr.gif', // seated piriformis stretch
  'plank': 'https://static.exercisedb.dev/media/VBAWRPG.gif', // weighted front plank
  'plank-hold': 'https://static.exercisedb.dev/media/VBAWRPG.gif', // weighted front plank
  'power-clean': 'https://static.exercisedb.dev/media/SiWCcTN.gif', // power clean
  'power-snatch': 'https://static.exercisedb.dev/media/dG5Smob.gif', // snatch pull
  'preacher-curl': 'https://static.exercisedb.dev/media/qOgPVf6.gif', // barbell preacher curl
  'preacher-curl-machine': 'https://static.exercisedb.dev/media/b6hQYMb.gif', // lever preacher curl
  'pull-ups': 'https://static.exercisedb.dev/media/lBDjFxJ.gif', // pull-up
  'push-press': 'https://static.exercisedb.dev/media/L0GJN9d.gif', // barbell push press
  'push-up': 'https://static.exercisedb.dev/media/I4hDWkc.gif', // push-up
  'push-ups': 'https://static.exercisedb.dev/media/I4hDWkc.gif', // push-up
  'quad-stretch': 'https://static.exercisedb.dev/media/Q5QilEh.gif', // standing single leg quad stretch
  'quadriceps-stretch': 'https://static.exercisedb.dev/media/Q5QilEh.gif', // standing single leg quad stretch (FIXED: different from hip-flexor)
  'rdl-machine': 'https://static.exercisedb.dev/media/GUT8I22.gif', // lever deadlift
  'rear-delt-flyes': 'https://static.exercisedb.dev/media/8DiFDVA.gif', // dumbbell rear fly
  'rear-delt-machine': 'https://static.exercisedb.dev/media/myfUsKf.gif', // lever seated reverse fly
  'reverse-lunges': 'https://static.exercisedb.dev/media/RRWFUcw.gif', // dumbbell lunge
  'reverse-pec-deck': 'https://static.exercisedb.dev/media/myfUsKf.gif', // lever seated reverse fly
  'reverse-wrist-curls': 'https://static.exercisedb.dev/media/LsZkfU6.gif', // barbell reverse wrist curl
  'romanian-deadlift': 'https://static.exercisedb.dev/media/wQ2c4XD.gif', // barbell romanian deadlift
  'rope-pushdown': 'https://static.exercisedb.dev/media/dU605di.gif', // cable pushdown (with rope attachment)
  'rowing': 'https://static.exercisedb.dev/media/H1PESYI.gif', // TODO: find specific rowing
  'rowing-machine': 'https://static.exercisedb.dev/media/H1PESYI.gif', // SHARED-WITH:rowing
  'running': 'https://static.exercisedb.dev/media/ealLwvX.gif', // SHARED-WITH:high-knees
  'russian-twists': 'https://static.exercisedb.dev/media/XVDdcoj.gif', // russian twist
  'scalene-stretch': 'https://static.exercisedb.dev/media/GSDioYu.gif', // TODO: find specific scalene
  'scapular-push-ups': 'https://static.exercisedb.dev/media/I4hDWkc.gif', // TODO: find specific scapular
  'seated-calf-raise': 'https://static.exercisedb.dev/media/bOOdeyc.gif', // lever seated calf raise
  'seated-hamstring-stretch': 'https://static.exercisedb.dev/media/yRYyfdA.gif', // exercise ball seated hamstring stretch
  'seated-leg-curl': 'https://static.exercisedb.dev/media/Zg3XY7P.gif', // lever seated leg curl
  'seated-overhead-press': 'https://static.exercisedb.dev/media/kTbSH9h.gif', // barbell seated overhead press (FIXED: correct for seated)
  'seated-row-machine': 'https://static.exercisedb.dev/media/7I6LNUG.gif', // lever seated row
  'seated-spinal-twist': 'https://static.exercisedb.dev/media/yRYyfdA.gif', // TODO: find specific spinal twist
  'shoulder-cross-body-stretch': 'https://static.exercisedb.dev/media/Z5YStHW.gif', // TODO: find specific cross-body
  'shoulder-dislocates': 'https://static.exercisedb.dev/media/VfMmJkR.gif', // TODO: find specific dislocates
  'shoulder-tap-plank': 'https://static.exercisedb.dev/media/yRpV5TC.gif', // shoulder tap
  'shrugs': 'https://static.exercisedb.dev/media/dG7tG5y.gif', // barbell shrug
  'side-plank': 'https://static.exercisedb.dev/media/X6ytgYZ.gif', // dumbbell side plank with rear fly
  'single-arm-cable-row': 'https://static.exercisedb.dev/media/vpp9Ku2.gif', // cable seated one arm alternate row
  'sissy-squat': 'https://static.exercisedb.dev/media/xdYPUtE.gif', // sissy squat
  'sit-ups': 'https://static.exercisedb.dev/media/W2LkxZg.gif', // SHARED-WITH:crunches
  'ski-erg': 'https://static.exercisedb.dev/media/vpQaQkH.gif', // ski ergometer
  'skull-crushers': 'https://static.exercisedb.dev/media/h8LFzo9.gif', // barbell lying triceps extension skull crusher
  'sled-push': 'https://static.exercisedb.dev/media/v0FWXIV.gif', // sled 45 degrees one leg press
  'smith-machine-bench-press': 'https://static.exercisedb.dev/media/M3lhw1g.gif', // smith bench press
  'smith-machine-calf-raise': 'https://static.exercisedb.dev/media/ykUOVze.gif', // SHARED-WITH:standing-calf-raise
  'smith-machine-hip-thrust': 'https://static.exercisedb.dev/media/OPqShYN.gif', // SHARED-WITH:hip-thrust-machine
  'smith-machine-incline-press': 'https://static.exercisedb.dev/media/5v7KYld.gif', // smith incline bench press
  'smith-machine-lunge': 'https://static.exercisedb.dev/media/HsjbB1z.gif', // smith sprint lunge
  'smith-machine-row': 'https://static.exercisedb.dev/media/ZX9UZmj.gif', // smith bent over row
  'smith-machine-shoulder-press': 'https://static.exercisedb.dev/media/vqsbmL0.gif', // lever shoulder press v. 2
  'smith-machine-shrug': 'https://static.exercisedb.dev/media/ZZKbeMw.gif', // lever shrug
  'smith-machine-squat': 'https://static.exercisedb.dev/media/jFtipLl.gif', // smith squat
  'smith-machine-upright-row': 'https://static.exercisedb.dev/media/1DN3iz4.gif', // smith upright row
  'soleus-stretch': 'https://static.exercisedb.dev/media/1LVFcEn.gif', // SHARED-WITH:calf-gastrocnemius-stretch
  'spider-curls': 'https://static.exercisedb.dev/media/qOgPVf6.gif', // SHARED-WITH:preacher-curl
  'split-squat': 'https://static.exercisedb.dev/media/t8iSghb.gif', // barbell lunge (FIXED: different from bulgarian-split-squat)
  'sprints': 'https://static.exercisedb.dev/media/ealLwvX.gif', // SHARED-WITH:running
  'squat-clean': 'https://static.exercisedb.dev/media/SiWCcTN.gif', // SHARED-WITH:power-clean
  'stair-climber': 'https://static.exercisedb.dev/media/SkRU9hI.gif', // TODO: find specific stair climber
  'stair-master': 'https://static.exercisedb.dev/media/SkRU9hI.gif', // ALIAS-OF:stair-climber
  'standing-calf-raise': 'https://static.exercisedb.dev/media/ykUOVze.gif', // lever standing calf raise
  'standing-quad-stretch': 'https://static.exercisedb.dev/media/Q5QilEh.gif', // SHARED-WITH:quadriceps-stretch
  'standing-side-bend-stretch': 'https://static.exercisedb.dev/media/f38OEuO.gif', // TODO: find specific side bend
  'stationary-bike': 'https://static.exercisedb.dev/media/H1PESYI.gif', // stationary bike run
  'step-ups': 'https://static.exercisedb.dev/media/aXtJhlg.gif', // dumbbell step-up
  'stiff-leg-deadlift': 'https://static.exercisedb.dev/media/hrVQWvE.gif', // barbell straight leg deadlift
  'straight-arm-pulldown': 'https://static.exercisedb.dev/media/x69MAlq.gif', // cable straight arm pulldown
  'sumo-deadlift': 'https://static.exercisedb.dev/media/KgI0tqW.gif', // barbell sumo deadlift
  'swimming': 'https://static.exercisedb.dev/media/H1PESYI.gif', // TODO: find specific swimming
  't-bar-row': 'https://static.exercisedb.dev/media/aaXr7ld.gif', // lever t bar row
  'thoracic-extension-stretch': 'https://static.exercisedb.dev/media/GSDioYu.gif', // TODO: find specific thoracic extension
  'thoracic-rotation-stretch': 'https://static.exercisedb.dev/media/DFGXwZr.gif', // TODO: find specific thoracic rotation
  'thoracic-rotations': 'https://static.exercisedb.dev/media/DFGXwZr.gif', // ALIAS-OF:thoracic-rotation-stretch
  'torso-twists': 'https://static.exercisedb.dev/media/XVDdcoj.gif', // SHARED-WITH:russian-twists
  'tricep-dip-machine': 'https://static.exercisedb.dev/media/X6C6i5Y.gif', // triceps dip
  'tricep-dips': 'https://static.exercisedb.dev/media/X6C6i5Y.gif', // triceps dip
  'tricep-extension-machine': 'https://static.exercisedb.dev/media/Ser9eQp.gif', // lever triceps extension
  'tricep-pushdown': 'https://static.exercisedb.dev/media/3ZflifB.gif', // cable pushdown
  'tricep-stretch': 'https://static.exercisedb.dev/media/Z5YStHW.gif', // SHARED-WITH:overhead-triceps-stretch
  'upper-trapezius-stretch': 'https://static.exercisedb.dev/media/GSDioYu.gif', // upper back stretch
  'upright-rows': 'https://static.exercisedb.dev/media/UDlhcO8.gif', // barbell upright row
  'walking-lunges': 'https://static.exercisedb.dev/media/IZVHb27.gif', // walking lunge
  'wall-angels': 'https://static.exercisedb.dev/media/VfMmJkR.gif', // TODO: find specific wall angels
  'woodchoppers': 'https://static.exercisedb.dev/media/wZLpgUK.gif', // TODO: find specific woodchopper
  'world-greatest-stretch': 'https://static.exercisedb.dev/media/DFGXwZr.gif', // world greatest stretch
  'wrist-curls': 'https://static.exercisedb.dev/media/82LxxkW.gif', // barbell wrist curl
  'wrist-extensor-stretch': 'https://static.exercisedb.dev/media/UtmIqcI.gif', // side wrist pull stretch
  'wrist-flexor-stretch': 'https://static.exercisedb.dev/media/UtmIqcI.gif', // side wrist pull stretch
};

/**
 * Get animation URL for an exercise.
 * @param exerciseId - The exercise ID to lookup
 * @returns The GIF URL or undefined if not mapped
 */
export function getExerciseAnimationUrl(exerciseId: string): string | undefined {
  return exerciseAnimationMap[exerciseId];
}
